version: '2.4'

services:

  web:
    build: ./server
    container_name: srcful-gw
    restart: always
    network_mode: host
    environment:
      - HOST_IP
      - REST_SERVICE_PORT=80 # should correspond to the port in the web service below
      - REST_SERVICE_PORT_INTERNAL=80 # should correspond to the port in the web service below
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    devices:
      - /dev/i2c-1
    volumes:
      - srcful-data:/data/srcful
      - /var/run/dbus:/host/run/dbus
    labels:
      io.balena.features.supervisor-api: 1  # needed to get the ip of the device when running on balena os in server/balena_get_host_ip.sh

  bluetooth:
    build: ./bluetooth
    container_name: ble
    privileged: true
    network_mode: host
    restart: always
    environment:
      - HOST_IP
      - REST_SERVICE_PORT=80
      - REST_SERVICE_PORT_INTERNAL=80
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    depends_on:
      - "web"
    volumes:
      - /var/run/dbus:/host/run/dbus
      - /sys:/sys
      - /lib/modules:/lib/modules


volumes:
  srcful-data: