# RPI4

version: "2.4"

x-environment: &shared_env
  - REST_SERVICE_PORT: 80 # should correspond to the port in the web service below
  - REST_SERVICE_PORT_INTERNAL: 80 # should correspond to the port in the web service below

services:
  web:
    build: ./server
    container_name: eGW-web
    ports:
      - 80:5000
    restart: always
    network_mode: host
    environment:
      <<: *shared_env
    devices:
      - /dev/i2c-1
    volumes:
      - srcful-data:/data/srcful
      - /var/run/dbus:/host/run/dbus

  bluetooth:
    build: ./bluetooth
    container_name: eGW-ble
    privileged: true
    network_mode: host
    environment:
      <<: *shared_env
      # GPIO_BUTTON_PIN: 7 # Uncomment if running on a RAK Hotspot V.2 for button
    volumes:
      - /var/run/dbus:/host/run/dbus
      - /sys:/sys
      - /lib/modules:/lib/modules
    restart: always
    depends_on:
      - web

volumes:
  srcful-data:
