# RAK Hotspot V.2 (LoRaWAN)

version: "2.4"

x-environment: &shared_env
  - REST_SERVICE_PORT: 80 # should correspond to the port in the web service below
  - REST_SERVICE_PORT_INTERNAL: 80 # should correspond to the port in the web service below

services:
  web:
    build: ./server
    container_name: eGW-web
    ports:
      - 80:5000
    restart: always
    network_mode: host
    environment:
      <<: *shared_env
    devices:
      - /dev/i2c-1
    volumes:
      - srcful-data:/data/srcful
      - /var/run/dbus:/host/run/dbus

  bluetooth:
    build: ./bluetooth
    container_name: eGW-ble
    privileged: true
    network_mode: host # could be needed for ble communication, test?
    environment:
      <<: *shared_env
      GPIO_BUTTON_PIN: 7
    volumes:
      - /var/run/dbus:/host/run/dbus
      - /sys:/sys
      - /lib/modules:/lib/modules
    restart: always
    depends_on:
      - web

  gateway-rs:
    build: ./gateway-rs
    network_mode: host
    devices:
      - /dev/i2c-1
    expose:
      - "1680"
    environment:
      - GATEWAY_SETTINGS=/app/settings.toml

  packet-forwarder:
    build: ./udp-packet-forwarder
    restart: no
    privileged: true # set this to true or define the required devices to share with the container under the `devices` tag below
    network_mode: host # required to read host interface MAC instead of virtual one, you don't need this if you set the GATEWAY_EUI manually

    environment:
      MODEL: "RAK7248"
      USE_LIBGPIOD: 1
      RESET_GPIO: 25
      HAS_GPS: 0

      # Set GPS_DEV to a dummy value to prevent the packet forwarder from trying to initialize the GPS
      GPS_DEV: /dev/null

      # Helium settings
      SERVER_HOST: 127.0.0.1
      SERVER_PORT: 1680
    depends_on:
      - gateway-rs

volumes:
  srcful-data:
