version: "2"
services:
  web_nc:
    build:
      context: ./server
      dockerfile: Dockerfile-no_crypt
    container_name: srcfull-gw
    restart: always
    privileged: true
    #network_mode: host
    volumes:
      - srcful-data:/var/srcful
    ports:
      - "8080:5000"
    #devices:
    #  - /dev/ttyACM0:/dev/ttyACM0 # bluethooth

volumes:
  srcful-data:
