# Srcful & Helium Gateway

version: "2.4"

x-environment: &shared_env
  - REST_SERVICE_PORT: 80 # should correspond to the port in the web service below
  - REST_SERVICE_PORT_INTERNAL: 5000 # should correspond to the port in the web service below

services:
  web:
    ports:
      - 80:5000
    build: ./server
    container_name: eGW-web
    restart: always
    environment:
      <<: *shared_env
    devices:
      - /dev/i2c-1
    labels:
      io.balena.features.dbus: 1 # needed for the wifi provisioning calls
      io.balena.features.supervisor-api: 1 # needed to get the ip of the device when running on balena os in server/balena_get_host_ip.sh
    volumes:
      - srcful-data:/data/srcful

  bluetooth:
    build: ./bluetooth
    container_name: eGW-ble
    privileged: true
    network_mode: host # could be needed for ble communication, test?
    environment:
      - REST_SERVICE_PORT=80 # should correspond to the port in the web service below
      - REST_SERVICE_PORT_INTERNAL=5000 # should correspond to the port in the web service below
      - GPIO_BUTTON_PIN=7
    restart: always
    labels:
      io.balena.features.dbus: 1 # needed for ble communication over bluez
      io.balena.features.kernel-modules: 1 # why needed? test?
      io.balena.features.sysfs: 1 # needed to set the bluetooth parameters in bluetooth/docker_entrypoint.sh
    depends_on:
      - web

  # gateway-rs:
  #   build: ./gateway-rs
  #   network_mode: host
  #   devices:
  #     - /dev/i2c-1
  #   expose:
  #     - "1680"
  #   environment:
  #     - GATEWAY_SETTINGS=/app/settings.toml
  #   depends_on:
  #     - packet-forwarder

  # packet-forwarder:
  #   # Use pre-defined image
  #   image: rakwireless/udp-packet-forwarder:latest
  #   restart: unless-stopped
  #   privileged: true # set this to true or define the required devices to share with the container under the `devices` tag below
  #   network_mode: host # required to read host interface MAC instead of virtual one, you don't need this if you set the GATEWAY_EUI manually

  #   environment:
  #     MODEL: "RAK7248"
  #     USE_LIBGPIOD: 0
  #     RESET_GPIO: 25
  #     HAS_GPS: 0

  #     # Set GPS_DEV to a dummy value to prevent the packet forwarder from trying to initialize the GPS
  #     GPS_DEV: /dev/null

  #     # Helium settings
  #     SERVER_HOST: 127.0.0.1
  #     SERVER_PORT: 1680

volumes:
  srcful-data:
