# SOLARIS

version: "2.4"

x-environment: &shared_env
  - REST_SERVICE_PORT: 80 # should correspond to the port in the web service below
  - REST_SERVICE_PORT_INTERNAL: 80 # should correspond to the port in the web service below

services:
  web:
    ports:
      - 80:5000
    build: ./server
    container_name: eGW-web
    restart: always
    network_mode: host
    environment:
      <<: *shared_env
    devices:
      - /dev/i2c-1
    labels:
      io.balena.features.dbus: 1 # needed for the wifi provisioning calls
      io.balena.features.supervisor-api: 1 # needed to get the ip of the device when running on balena os in server/balena_get_host_ip.sh
    volumes:
      - srcful-data:/data/srcful

  bluetooth:
    build: ./bluetooth
    container_name: eGW-ble
    privileged: true
    network_mode: host # could be needed for ble communication, test?
    environment:
      - REST_SERVICE_PORT=80 # should correspond to the port in the web service below
      - REST_SERVICE_PORT_INTERNAL=80 # should correspond to the port in the web service below
      - GPIO_BUTTON_PIN=7
    restart: always
    labels:
      io.balena.features.dbus: 1 # needed for ble communication over bluez
      io.balena.features.kernel-modules: 1 # why needed? test?
      io.balena.features.sysfs: 1 # needed to set the bluetooth parameters in bluetooth/docker_entrypoint.sh
    depends_on:
      - "web"

volumes:
  srcful-data:
