from ..profile_keys import (
    ProtocolKey,
    ProfileKey,
    RegistersKey,
    FunctionCodeKey,
    DeviceCategoryKey,
    DataTypeKey,
    EndiannessKey,
)

supported_devices = {
    DeviceCategoryKey.INVERTERS: [
        {
            ProfileKey.NAME: "huawei",
            ProfileKey.MAKER: "Huawei",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Huawei",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Another inverter profile...",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 30015,
                RegistersKey.NUM_OF_REGISTERS: 10,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 30000,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 32000,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 32085,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 32064,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.I32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 0.001,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["huawei", "sun2000"],
        },
        {
            ProfileKey.NAME: "solaredge",
            ProfileKey.MAKER: "SolarEdge",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "SolarEdge",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "SolarEdge inverter profile",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 40052,
                RegistersKey.NUM_OF_REGISTERS: 16,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40000,
                    RegistersKey.NUM_OF_REGISTERS: 69,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40069,
                    RegistersKey.NUM_OF_REGISTERS: 33,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40106,
                    RegistersKey.NUM_OF_REGISTERS: 3,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40121,
                    RegistersKey.NUM_OF_REGISTERS: 70,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40085,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40100,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.I16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["solaredge"],
        },
        {
            ProfileKey.NAME: "solaredge_us",
            ProfileKey.MAKER: "SolarEdge",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "SolarEdge US",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "SolarEdge US inverter profile",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 40052,
                RegistersKey.NUM_OF_REGISTERS: 16,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40000,
                    RegistersKey.NUM_OF_REGISTERS: 69,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40069,
                    RegistersKey.NUM_OF_REGISTERS: 33,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40106,
                    RegistersKey.NUM_OF_REGISTERS: 3,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40121,
                    RegistersKey.NUM_OF_REGISTERS: 70,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40085,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.001,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40100,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.I16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 0.001,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["solaredge"],
        },
        {
            ProfileKey.NAME: "sungrow",
            ProfileKey.MAKER: "Sungrow",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Sungrow",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Another inverter profile...",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                RegistersKey.START_REGISTER: 4989,
                RegistersKey.NUM_OF_REGISTERS: 10,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 4989,
                    RegistersKey.NUM_OF_REGISTERS: 120,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5112,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5035,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5016,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.U32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["sungrow", "Espressif"],
        },
        {
            ProfileKey.NAME: "sungrow_sf",
            ProfileKey.MAKER: "Sungrow",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Sungrow SF",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Sungrow Scale Factor inverter profile",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                RegistersKey.START_REGISTER: 4989,
                RegistersKey.NUM_OF_REGISTERS: 10,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 4989,
                    RegistersKey.NUM_OF_REGISTERS: 120,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5112,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5035,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5016,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.U32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["sungrow", "Espressif"],
        },
        {
            ProfileKey.NAME: "sma",
            ProfileKey.MAKER: "SMA",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "SMA",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Another inverter profile...",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                RegistersKey.START_REGISTER: 40067,
                RegistersKey.NUM_OF_REGISTERS: 2,
                RegistersKey.DATA_TYPE: DataTypeKey.U32,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 30000,
                    RegistersKey.NUM_OF_REGISTERS: 10,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 30051,
                    RegistersKey.NUM_OF_REGISTERS: 10,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 30775,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 31085,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 30803,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.U32,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 30775,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.I32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["sma"],
        },
        {
            ProfileKey.NAME: "fronius",
            ProfileKey.MAKER: "Fronius",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Fronius",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Fronius float inverter profile",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 40052,
                RegistersKey.NUM_OF_REGISTERS: 16,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40000,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                }
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40093,  # float map v1.0
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.F32,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40107,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.F32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["fronius", "u-blox ag"],
        },
        {
            ProfileKey.NAME: "fronius_sf",
            ProfileKey.MAKER: "Fronius",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Fronius SF",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Fronius SF inverter profile",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 40052,
                RegistersKey.NUM_OF_REGISTERS: 16,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40000,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                }
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40085,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 40100,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.I16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["fronius", "u-blox ag"],
        },
        {
            ProfileKey.NAME: "deye",
            ProfileKey.MAKER: "Deye",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Deye",
            ProfileKey.PROTOCOL: ProtocolKey.SOLARMAN,
            ProfileKey.DESCRIPTION: "Another inverter profile...",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 3,
                RegistersKey.NUM_OF_REGISTERS: 8,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 0,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 125,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 250,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 375,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 500,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 625,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 750,
                    RegistersKey.NUM_OF_REGISTERS: 51,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 609,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 672,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["deye", "high-flying"],
        },
        {
            ProfileKey.NAME: "deye_micro",
            ProfileKey.MAKER: "Deye",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Deye Micro-inverter",
            ProfileKey.PROTOCOL: ProtocolKey.SOLARMAN,
            ProfileKey.DESCRIPTION: "Another inverter profile...",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 3,
                RegistersKey.NUM_OF_REGISTERS: 8,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 0,
                    RegistersKey.NUM_OF_REGISTERS: 120,
                }
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 79,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 109,
                    RegistersKey.NUM_OF_REGISTERS: 2,  # First register is the voltage, second is the current
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "PV 1 Power",
                    RegistersKey.SCALE_FACTOR: 0.1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 111,
                    RegistersKey.NUM_OF_REGISTERS: 2,  # First register is the voltage, second is the current
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "PV 2 Power",
                    RegistersKey.SCALE_FACTOR: 0.1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 113,
                    RegistersKey.NUM_OF_REGISTERS: 2,  # First register is the voltage, second is the current
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "PV 3 Power",
                    RegistersKey.SCALE_FACTOR: 0.1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["deye", "high-flying"],
        },
        {
            ProfileKey.NAME: "growatt",
            ProfileKey.MAKER: "Growatt",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Growatt",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Another inverter profile...",
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 0,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 125,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 1000,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3000,
                    RegistersKey.NUM_OF_REGISTERS: 125,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 37,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3001,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.U32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 0.1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["growatt", "high-flying"],
        },
        {
            ProfileKey.NAME: "goodwe",
            ProfileKey.MAKER: "GoodWe",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "GoodWe",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Another inverter profile...",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 35003,
                RegistersKey.NUM_OF_REGISTERS: 8,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 35000,
                    RegistersKey.NUM_OF_REGISTERS: 40,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 35100,
                    RegistersKey.NUM_OF_REGISTERS: 40,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 35141,
                    RegistersKey.NUM_OF_REGISTERS: 40,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 35182,
                    RegistersKey.NUM_OF_REGISTERS: 40,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 36000,
                    RegistersKey.NUM_OF_REGISTERS: 44,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 37000,
                    RegistersKey.NUM_OF_REGISTERS: 23,
                }
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 35123,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 35138,
                    RegistersKey.NUM_OF_REGISTERS: 1,  # PV1. First register is the voltage, second is the current
                    RegistersKey.DATA_TYPE: DataTypeKey.I16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "PV 1 Power",
                    RegistersKey.SCALE_FACTOR: 0.1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["goodwe", "high-flying"],
        },
        {
            ProfileKey.NAME: "ferroamp",
            ProfileKey.MAKER: "Ferroamp",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Ferroamp",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Another inverter profile...",
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 1004,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 1008,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2000,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2016,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2032,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2036,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2040,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2044,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2064,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2068,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2100,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2104,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2108,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2112,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2116,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2120,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2124,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2128,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2132,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2136,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2140,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2144,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5000,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5002,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5004,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5064,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5100,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 2016,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.F32,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.LITTLE,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 5100,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.F32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.LITTLE,
                },
            ],
            ProfileKey.KEYWORDS: ["ferroamp"],
        },
        {
            ProfileKey.NAME: "sofar",
            ProfileKey.MAKER: "Sofar",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Sofar",
            ProfileKey.PROTOCOL: ProtocolKey.SOLARMAN,
            ProfileKey.DESCRIPTION: "Another inverter profile...",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 1093,
                RegistersKey.NUM_OF_REGISTERS: 8,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1024,
                    RegistersKey.NUM_OF_REGISTERS: 50
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1088,
                    RegistersKey.NUM_OF_REGISTERS: 32
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1152,
                    RegistersKey.NUM_OF_REGISTERS: 48
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1280,
                    RegistersKey.NUM_OF_REGISTERS: 34
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1408,
                    RegistersKey.NUM_OF_REGISTERS: 52,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1472,
                    RegistersKey.NUM_OF_REGISTERS: 4
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1536,
                    RegistersKey.NUM_OF_REGISTERS: 60
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1600,
                    RegistersKey.NUM_OF_REGISTERS: 32
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1664,
                    RegistersKey.NUM_OF_REGISTERS: 28
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1156,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1414,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "PV 1 Power",
                    RegistersKey.SCALE_FACTOR: 0.1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1417,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "PV 2 Power",
                    RegistersKey.SCALE_FACTOR: 0.1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1420,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "PV 3 Power",
                    RegistersKey.SCALE_FACTOR: 0.1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1544,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "%",
                    RegistersKey.DESCRIPTION: "Battery 1 SOC",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 1551,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "%",
                    RegistersKey.DESCRIPTION: "Battery 2 SOC",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["sofar"],
        },
        {
            ProfileKey.NAME: "solis",
            ProfileKey.MAKER: "Solis",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Solis",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Solis inverter profile",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                RegistersKey.START_REGISTER: 3060,
                RegistersKey.NUM_OF_REGISTERS: 4,
                RegistersKey.DATA_TYPE: DataTypeKey.U64,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 35000,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3000,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3050,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3100,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3150,
                    RegistersKey.NUM_OF_REGISTERS: 12,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3162,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3212,
                    RegistersKey.NUM_OF_REGISTERS: 49,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3261,
                    RegistersKey.NUM_OF_REGISTERS: 27,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3289,
                    RegistersKey.NUM_OF_REGISTERS: 28,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3321,
                    RegistersKey.NUM_OF_REGISTERS: 18,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3339,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3389,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3439,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3489,
                    RegistersKey.NUM_OF_REGISTERS: 11,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3500,
                    RegistersKey.NUM_OF_REGISTERS: 20,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3530,
                    RegistersKey.NUM_OF_REGISTERS: 37,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3570,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3620,
                    RegistersKey.NUM_OF_REGISTERS: 18,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3650,
                    RegistersKey.NUM_OF_REGISTERS: 40,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3700,
                    RegistersKey.NUM_OF_REGISTERS: 23,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3733,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3783,
                    RegistersKey.NUM_OF_REGISTERS: 17,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33601,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33651,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33701,
                    RegistersKey.NUM_OF_REGISTERS: 5,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3042,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 3006,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.U32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["solis", "Espressif"],
        },
        {
            ProfileKey.NAME: "solis_hybrid",
            ProfileKey.MAKER: "Solis",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Solis Hybrid",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Solis inverter profile",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                RegistersKey.START_REGISTER: 33004,
                RegistersKey.NUM_OF_REGISTERS: 15,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33000,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33050,
                    RegistersKey.NUM_OF_REGISTERS: 9,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33071,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33121,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33171,
                    RegistersKey.NUM_OF_REGISTERS: 11,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33200,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33250,
                    RegistersKey.NUM_OF_REGISTERS: 50,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33300,
                    RegistersKey.NUM_OF_REGISTERS: 38,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 35000,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33094,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 33057,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.U32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["solis", "Espressif"],
        },
        {
            ProfileKey.NAME: "Solax",
            ProfileKey.MAKER: "Solax",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Solax",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Solax inverter profile",
            ProfileKey.SN: {
                RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                RegistersKey.START_REGISTER: 0,
                RegistersKey.NUM_OF_REGISTERS: 7,
                RegistersKey.DATA_TYPE: DataTypeKey.STR,
                RegistersKey.UNIT: "",
                RegistersKey.DESCRIPTION: "Serial number",
                RegistersKey.SCALE_FACTOR: 1,
                RegistersKey.ENDIANNESS: EndiannessKey.BIG,
            },
            ProfileKey.REGISTERS_VERBOSE: [
                # The holding registers are not used in this case since they will be overwritten by the
                # input registers due to overlapping register addresses.
                # {
                #     RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                #     RegistersKey.START_REGISTER: 0,
                #     RegistersKey.NUM_OF_REGISTERS: 110,
                # },
                # {
                #     RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                #     RegistersKey.START_REGISTER: 110,
                #     RegistersKey.NUM_OF_REGISTERS: 110,
                # },
                # {
                #     RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                #     RegistersKey.START_REGISTER: 220,
                #     RegistersKey.NUM_OF_REGISTERS: 110,
                # },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 0,
                    RegistersKey.NUM_OF_REGISTERS: 110,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 110,
                    RegistersKey.NUM_OF_REGISTERS: 110,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 220,
                    RegistersKey.NUM_OF_REGISTERS: 110,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 7,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 10,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power 1",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 11,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "DC Power 2",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["Solax", "Espressif"],
        },
        {
            ProfileKey.NAME: "unknown",
            ProfileKey.MAKER: "Unknown",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "Unknown",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Unknown device profile...",
            ProfileKey.REGISTERS_VERBOSE: [],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_HOLDING_REGISTERS,
                    RegistersKey.START_REGISTER: 0,
                    RegistersKey.NUM_OF_REGISTERS: 1,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 0.01,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["unknown"],
        }
    ],
    DeviceCategoryKey.METERS: [
        {
            ProfileKey.NAME: "lqt40s",
            ProfileKey.MAKER: "LQT",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "LQT40S",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Another meter profile...",
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 0,
                    RegistersKey.NUM_OF_REGISTERS: 30,
                }
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 0,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.F32,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 24,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.F32,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "Active Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["lqt40s"],
        },
        {
            ProfileKey.NAME: "sdm630",
            ProfileKey.MAKER: "Eastron",
            ProfileKey.VERSION: "V1.1b3",
            ProfileKey.VERBOSE_ALWAYS: False,
            ProfileKey.DISPLAY_NAME: "SDM630",
            ProfileKey.PROTOCOL: ProtocolKey.MODBUS,
            ProfileKey.DESCRIPTION: "Another meter profile...",
            ProfileKey.REGISTERS_VERBOSE: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 0,
                    RegistersKey.NUM_OF_REGISTERS: 100,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 100,
                    RegistersKey.NUM_OF_REGISTERS: 100,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 200,
                    RegistersKey.NUM_OF_REGISTERS: 100,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 300,
                    RegistersKey.NUM_OF_REGISTERS: 100,
                },
            ],
            ProfileKey.REGISTERS: [
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 70,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.F32,
                    RegistersKey.UNIT: "Hz",
                    RegistersKey.DESCRIPTION: "Grid frequency",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
                {
                    RegistersKey.FUNCTION_CODE: FunctionCodeKey.READ_INPUT_REGISTERS,
                    RegistersKey.START_REGISTER: 52,
                    RegistersKey.NUM_OF_REGISTERS: 2,
                    RegistersKey.DATA_TYPE: DataTypeKey.U16,
                    RegistersKey.UNIT: "W",
                    RegistersKey.DESCRIPTION: "Active Power",
                    RegistersKey.SCALE_FACTOR: 1,
                    RegistersKey.ENDIANNESS: EndiannessKey.BIG,
                },
            ],
            ProfileKey.KEYWORDS: ["sdm630"],
        }
    ],
}
