entryPoints:
  web:
    address: ":80"
  dashboard:
    address: ":8080"

api:
  dashboard: true
  insecure: true
  # Important: Specify the dashboard entrypoint
  entryPoint: dashboard

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true