entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true
  # Important: Specify the dashboard entrypoint

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true