# traefik/traefik.yml
entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

# Use static configuration instead of Docker provider
providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true