FROM python:3.11-alpine
COPY . /server
ENV CRYPTOAUTHLIB_NOUSB=True
RUN pip install --upgrade pip
RUN pip install pymodbus
RUN pip install requests
RUN pip install typing-extensions
EXPOSE 5000

ENTRYPOINT ["python"]
CMD ["-m", "server", "-b", "/var/srcful/bootstrap.txt"]