SOLAREDGE = "solaredge"
SUNGROW = "sungrow"
SUNGROW_HYBRID = "sungrow_hybrid"
HUAWEI = "huawei"
GROWATT = "growatt"
LQT40S = "lqt40s"
UNKNOWN = "unknown"

OPERATION = "operation"
READ_INPUT = 0x04
READ_HOLDING = 0x03

SCAN_START = "scan_start"
SCAN_RANGE = "scan_range"




INVERTERS = {

    UNKNOWN: [
        {OPERATION: READ_INPUT, SCAN_START: 30000, SCAN_RANGE: 1}
    ],

    GROWATT: [
        {OPERATION: READ_INPUT, SCAN_START: 0, SCAN_RANGE: 92},
    ],

    SUNGROW: [
        {OPERATION: READ_INPUT, SCAN_START: 4999, SCAN_RANGE: 110},
        {OPERATION: READ_INPUT, SCAN_START: 5112, SCAN_RANGE: 50},
    ],

    SUNGROW_HYBRID: [
        {OPERATION: READ_INPUT, SCAN_START: 4999, SCAN_RANGE: 110},
        {OPERATION: READ_INPUT, SCAN_START: 5112, SCAN_RANGE: 50},
        {OPERATION: READ_INPUT, SCAN_START: 13000, SCAN_RANGE: 6},
        {OPERATION: READ_INPUT, SCAN_START: 13028, SCAN_RANGE: 6},
    ],

    SOLAREDGE: [
        {OPERATION: READ_HOLDING, SCAN_START: 40000, SCAN_RANGE: 61},
        {OPERATION: READ_HOLDING, SCAN_START: 40069, SCAN_RANGE: 37},
        {OPERATION: READ_HOLDING, SCAN_START: 40121, SCAN_RANGE: 70},
    ],

    HUAWEI: [
        {OPERATION: READ_HOLDING, SCAN_START: 30000, SCAN_RANGE: 35},
        {OPERATION: READ_HOLDING, SCAN_START: 32064, SCAN_RANGE: 31}

        # {OPERATION: READ_HOLDING, SCAN_START: 30000, SCAN_RANGE: 35},
        # {OPERATION: READ_HOLDING, SCAN_START: 30070, SCAN_RANGE: 13},
        # {OPERATION: READ_HOLDING, SCAN_START: 32000, SCAN_RANGE: 1},
        # {OPERATION: READ_HOLDING, SCAN_START: 32002, SCAN_RANGE: 3},
        # {OPERATION: READ_HOLDING, SCAN_START: 32008, SCAN_RANGE: 3},
        # {OPERATION: READ_HOLDING, SCAN_START: 32016, SCAN_RANGE: 8},
        # {OPERATION: READ_HOLDING, SCAN_START: 32064, SCAN_RANGE: 31},
        # {OPERATION: READ_HOLDING, SCAN_START: 32106, SCAN_RANGE: 2},
        # {OPERATION: READ_HOLDING, SCAN_START: 32114, SCAN_RANGE: 2},
        # {OPERATION: READ_HOLDING, SCAN_START: 35300, SCAN_RANGE: 8},
        # {OPERATION: READ_HOLDING, SCAN_START: 37113, SCAN_RANGE: 2},
        # {OPERATION: READ_HOLDING, SCAN_START: 37200, SCAN_RANGE: 3},
        # {OPERATION: READ_HOLDING, SCAN_START: 40000, SCAN_RANGE: 2},
        # {OPERATION: READ_HOLDING, SCAN_START: 40037, SCAN_RANGE: 2},
        # {OPERATION: READ_HOLDING, SCAN_START: 40120, SCAN_RANGE: 1},
        # {OPERATION: READ_HOLDING, SCAN_START: 40122, SCAN_RANGE: 2},
        # {OPERATION: READ_HOLDING, SCAN_START: 40125, SCAN_RANGE: 3},
        # {OPERATION: READ_HOLDING, SCAN_START: 40129, SCAN_RANGE: 2},
        # {OPERATION: READ_HOLDING, SCAN_START: 40134, SCAN_RANGE: 64},
        # {OPERATION: READ_HOLDING, SCAN_START: 40198, SCAN_RANGE: 1},
        # {OPERATION: READ_HOLDING, SCAN_START: 40198, SCAN_RANGE: 1},
        # # Startup
        # {OPERATION: READ_HOLDING, SCAN_START: 40200, SCAN_RANGE: 1},
        # # Shutdown
        # {OPERATION: READ_HOLDING, SCAN_START: 40201, SCAN_RANGE: 1},
    ],

    LQT40S: [
        {OPERATION: READ_INPUT, SCAN_START: 0, SCAN_RANGE: 2},
    ],
}
